# Generated by Django 4.2.23 on 2025-06-14 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_disease_image_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='timestamp',
            new_name='createAt',
        ),
        migrations.AddField(
            model_name='disease',
            name='updateAt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='health_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('disease_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.disease')),
            ],
        ),
    ]
