# Generated by Django 4.2.23 on 2025-06-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_timestamp_disease_createat_disease_updateat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='timestamp',
            new_name='createAt',
        ),
        migrations.AddField(
            model_name='medicine',
            name='updateAt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
