# Generated by Django 4.2.23 on 2025-06-14 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_timestamp_medicine_createat_medicine_updateat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Health_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_parameter_name', models.JSONField(default=list)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateAt', models.CharField(blank=True, max_length=255, null=True)),
                ('disease_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.disease')),
                ('parameter_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.health_parameters')),
            ],
        ),
    ]
