# Generated by Django 4.2.23 on 2025-06-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_sub_health_parameters_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_health_parameters',
            name='sub_parameter_name',
        ),
        migrations.DeleteModel(
            name='sub_health_parameters_name',
        ),
        migrations.AddField(
            model_name='sub_health_parameters',
            name='sub_parameter_name',
            field=models.JSONField(default=list),
        ),
    ]
