# Generated by Django 4.2.23 on 2025-06-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_sub_health_parameters_sub_parameter_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ask_to_expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subhealthparameter', models.JSONField(default=list)),
            ],
        ),
    ]
