# Generated by Django 4.2.23 on 2025-06-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_ask_to_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask_to_expert',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='dietary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.disease'),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='exercise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='health_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='healthparameter',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.health_parameters'),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='productId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='sleep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='stress_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='updatedAt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ask_to_expert',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ask_to_expert',
            name='subhealthparameter',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
