# Generated by Django 4.2.23 on 2025-06-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_ask_to_expert_age_ask_to_expert_allergies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='updateAt',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='updateAt',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='sub_health_parameters',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='sub_health_parameters',
            old_name='updateAt',
            new_name='updatedAt',
        ),
    ]
