# Generated by Django 4.2.23 on 2025-06-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ask_to_expert'),
        ),
    ]
