# Generated by Django 4.2.23 on 2025-06-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_user_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
