# Generated by Django 4.2.23 on 2025-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_order_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updatedAt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
